Remove unused code.
This was causing test failures:

  java.lang.IllegalStateException: Tests may not have parameters!
	at vogar.target.junit.Junit.getSuiteMethods(Junit.java:114)
	at vogar.target.junit.Junit.classToVogarTests(Junit.java:94)
	at vogar.target.junit.JUnitRunner.run(JUnitRunner.java:68)
	at vogar.target.TestRunner.run(TestRunner.java:236)
	at vogar.target.TestRunner.run(TestRunner.java:170)
	at vogar.target.TestRunner.main(TestRunner.java:249)

Change-Id: If2ca90b53eba08b3578645dad1aa5192d0d22d65